var articulos = [
    {
        id: 1,
        slug: 'playstation-5',
        nombre: 'PlayStation 5',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Consolas',
        precio: 6000,
        descripcion: 'Consola de nueva generacion con SSD de alta velocidad, graficos 4K y control DualSense.',
        detalles: ['Control DualSense incluido.', 'Salida de video hasta 4K.', 'Almacenamiento SSD de alta velocidad.'],
        imagenUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6566/6566040_sd.jpg',
        destacado: true,
        popular: true,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'inicio-populares', 'ps-consolas']
    },
    {
        id: 2,
        slug: 'ps4-reacondicionada',
        nombre: 'PS4 Reacondicionada',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Consolas',
        precio: 2800,
        descripcion: 'Consola PlayStation 4 revisada, lista para juegos fisicos y digitales.',
        detalles: ['Incluye control compatible.', 'Ideal para catalogo PS4.', 'Equipo revisado antes de entrega.'],
        imagenUrl: 'https://th.bing.com/th/id/R.d30ea10d7ceb8c3e040d628b8a69e292?rik=LYDmX6wmQ8svpw&riu=http%3a%2f%2fcdn.wccftech.com%2fwp-content%2fuploads%2f2015%2f02%2fplaystation_4_console_controller_ps4_92842_3840x2160.jpg&ehk=Bz0RQDd25gnzHttX2cWJWJIduJvdqZs%2faM7N2bhMeB0%3d&risl=&pid=ImgRaw&r=0',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['ps-consolas']
    },
    {
        id: 3,
        slug: 'ps5-slim',
        nombre: 'PS5 Slim',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Consolas',
        precio: 6200,
        descripcion: 'Version compacta de PlayStation 5 con gran rendimiento y diseno renovado.',
        detalles: ['Formato mas delgado.', 'Compatible con juegos PS5.', 'Alto rendimiento para 4K.'],
        imagenUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6566/6566040_sd.jpg',
        destacado: true,
        popular: false,
        ultimaSalida: true,
        listas: ['inicio-destacados', 'inicio-ultimas-salidas', 'ps-consolas']
    },
    {
        id: 4,
        slug: 'pack-playstation',
        nombre: 'Pack PlayStation',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Consolas',
        precio: 6900,
        descripcion: 'Pack pensado para empezar a jugar con consola y accesorios esenciales.',
        detalles: ['Consola PlayStation.', 'Control incluido.', 'Accesorios para instalacion inicial.'],
        imagenUrl: 'https://areajugones.sport.es/wp-content/uploads/2020/09/ps5-accesorios-1.jpeg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'ps-consolas']
    },
    {
        id: 5,
        slug: 'god-of-war-ragnarok',
        nombre: 'God of War Ragnarok',
        marca: 'PlayStation Studios',
        plataforma: 'PlayStation',
        tipo: 'Juegos',
        precio: 500,
        descripcion: 'Juego de accion y aventura ambientado en la mitologia nordica.',
        detalles: ['Historia cinematica.', 'Combate de accion.', 'Disponible para PlayStation.'],
        imagenUrl: 'https://playgamer.com.ar/wp-content/uploads/2023/11/god-of-war-ragnarok-ps5-portada.png',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['inicio-populares', 'ps-juegos', 'games-ps']
    },
    {
        id: 6,
        slug: 'spider-man-2',
        nombre: 'Spider-Man 2',
        marca: 'Insomniac Games',
        plataforma: 'PlayStation',
        tipo: 'Juegos',
        precio: 520,
        descripcion: 'Aventura de superheroes con exploracion urbana, combate dinamico y accion cinematica.',
        detalles: ['Exclusivo de PlayStation.', 'Mundo abierto.', 'Modo historia.'],
        imagenUrl: 'https://juegosdigitalesbolivia.com/files/images/productos/1764374148-marvels-spider-man-2-ps5-0.webp',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['inicio-populares', 'inicio-ultimas-salidas', 'ps-juegos', 'games-ps', 'games-ultimas']
    },
    {
        id: 7,
        slug: 'the-last-of-us-part-i',
        nombre: 'The Last of Us Part I',
        marca: 'Naughty Dog',
        plataforma: 'PlayStation',
        tipo: 'Juegos',
        precio: 450,
        descripcion: 'Aventura narrativa de supervivencia con ambientacion intensa y gran apartado visual.',
        detalles: ['Modo historia.', 'Remake para nueva generacion.', 'Genero accion y aventura.'],
        imagenUrl: 'https://www.picclickimg.com/6SMAAOSwMxRjEba~/PS5-The-Last-of-Us-Part-1-Remake.webp',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['ps-juegos', 'games-ps']
    },
    {
        id: 8,
        slug: 'final-fantasy-xvi',
        nombre: 'Final Fantasy XVI',
        marca: 'Square Enix',
        plataforma: 'PlayStation / Xbox',
        tipo: 'Juegos',
        precio: 480,
        descripcion: 'RPG de accion con combates espectaculares, fantasia oscura y narrativa extensa.',
        detalles: ['RPG de accion.', 'Campana individual.', 'Disponible en consolas seleccionadas.'],
        imagenUrl: 'https://gamefaqs.gamespot.com/a/box/8/1/1/909811_front.jpg',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['ps-juegos', 'xbox-juegos', 'games-ps', 'games-xbox', 'games-ultimas']
    },
    {
        id: 9,
        slug: 'dualsense-limited-edition',
        nombre: 'DualSense Limited Edition',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Mandos',
        precio: 850,
        descripcion: 'Control DualSense en edicion especial para PlayStation 5.',
        detalles: ['Respuesta haptica.', 'Gatillos adaptativos.', 'Conexion inalambrica.'],
        imagenUrl: 'https://m.media-amazon.com/images/I/612tbnqp-6L._AC_SX425_.jpg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['ps-accesorios', 'acces-mandos']
    },
    {
        id: 10,
        slug: 'pulse-3d-headset',
        nombre: 'Pulse 3D Headset',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Auriculares',
        precio: 1200,
        descripcion: 'Auriculares para PlayStation con audio envolvente y diseno comodo.',
        detalles: ['Audio 3D.', 'Microfono integrado.', 'Conexion inalambrica.'],
        imagenUrl: 'https://static.digit.in/default/b7ca7a45071ae1b7c7e58b6d21e109afd5005d9a.jpeg',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['ps-accesorios', 'acces-auriculares']
    },
    {
        id: 11,
        slug: 'base-y-control-ps5',
        nombre: 'Base y control PS5',
        marca: 'Sony',
        plataforma: 'PlayStation',
        tipo: 'Accesorios',
        precio: 950,
        descripcion: 'Combo para completar el setup de PlayStation 5 con base y control.',
        detalles: ['Accesorio para PS5.', 'Ideal para setup principal.', 'Incluye control.'],
        imagenUrl: 'https://areajugones.sport.es/wp-content/uploads/2020/09/ps5-accesorios-1.jpeg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['ps-accesorios']
    },
    {
        id: 12,
        slug: 'xbox-series-x',
        nombre: 'Xbox Series X',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Consolas',
        precio: 5800,
        descripcion: 'Consola Xbox de alto rendimiento para juegos en 4K y experiencia next-gen.',
        detalles: ['Potencia para 4K.', 'Compatible con Game Pass.', 'SSD de alta velocidad.'],
        imagenUrl: 'https://cdn.alfabetajuega.com/alfabetajuega/2020/09/Xbox-Series-X-caja-10092020.jpg',
        destacado: true,
        popular: true,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'inicio-populares', 'xbox-consolas']
    },
    {
        id: 13,
        slug: 'xbox-series-s',
        nombre: 'Xbox Series S',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Consolas',
        precio: 4200,
        descripcion: 'Consola compacta y digital para disfrutar juegos actuales con excelente rendimiento.',
        detalles: ['Formato digital.', 'Diseno compacto.', 'Compatible con Game Pass.'],
        imagenUrl: 'https://cms-assets.xboxservices.com/assets/bf/b0/bfb06f23-4c87-4c58-b4d9-ed25d3a739b9.png?n=389964_Hero-Gallery-0_A1_857x676.png',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['xbox-consolas']
    },
    {
        id: 14,
        slug: 'xbox-series-x-digital',
        nombre: 'Xbox Series X Digital',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Consolas',
        precio: 5400,
        descripcion: 'Xbox Series X en version digital para una biblioteca sin discos.',
        detalles: ['Sin lector de discos.', 'Rendimiento Series X.', 'Ideal para biblioteca digital.'],
        imagenUrl: 'https://cdn.alfabetajuega.com/alfabetajuega/2020/09/Xbox-Series-X-caja-10092020.jpg',
        destacado: false,
        popular: false,
        ultimaSalida: true,
        listas: ['inicio-ultimas-salidas', 'xbox-consolas']
    },
    {
        id: 15,
        slug: 'xbox-series-s-starter',
        nombre: 'Xbox Series S Starter',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Consolas',
        precio: 3900,
        descripcion: 'Pack inicial de Xbox Series S para entrar rapido al ecosistema Xbox.',
        detalles: ['Consola Series S.', 'Formato compacto.', 'Buena opcion de entrada.'],
        imagenUrl: 'https://www.notebookcheck.org/fileadmin/Notebooks/News/_nc3/Xbox_Series_S_Starter_Bundle.jpg',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['xbox-consolas']
    },
    {
        id: 16,
        slug: 'xbox-game-pass',
        nombre: 'Xbox Game Pass',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Juegos',
        precio: 120,
        descripcion: 'Suscripcion para acceder a un catalogo amplio de juegos de Xbox.',
        detalles: ['Catalogo por suscripcion.', 'Juegos variados.', 'Ideal para probar titulos.'],
        imagenUrl: 'https://static0.gamerantimages.com/wordpress/wp-content/uploads/2024/11/game-pass-streaming.jpg',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['xbox-juegos']
    },
    {
        id: 17,
        slug: 'fifa-25',
        nombre: 'FIFA 25',
        marca: 'EA Sports',
        plataforma: 'Multiplataforma',
        tipo: 'Juegos',
        precio: 500,
        descripcion: 'Juego de futbol con plantillas actualizadas, modos competitivos y partidos locales.',
        detalles: ['Deportes.', 'Multijugador.', 'Disponible en varias consolas.'],
        imagenUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROcRl8ojCbtZJK8VNfJQFAnH1ZRGG_InXjwA&s',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['xbox-juegos', 'games-xbox', 'games-ultimas']
    },
    {
        id: 18,
        slug: 'control-xbox-elite',
        nombre: 'Control Xbox Elite',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Mandos',
        precio: 1200,
        descripcion: 'Mando premium para Xbox con opciones de personalizacion y mejor precision.',
        detalles: ['Botones configurables.', 'Construccion premium.', 'Pensado para juego competitivo.'],
        imagenUrl: 'https://m.media-amazon.com/images/I/41Olt1+b1hL._SS500_.jpg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['xbox-accesorios', 'acces-mandos']
    },
    {
        id: 19,
        slug: 'control-xbox',
        nombre: 'Control Xbox',
        marca: 'Microsoft',
        plataforma: 'Xbox',
        tipo: 'Mandos',
        precio: 700,
        descripcion: 'Mando inalambrico para Xbox con diseno ergonomico y conectividad estable.',
        detalles: ['Conexion inalambrica.', 'Diseno ergonomico.', 'Compatible con Xbox y PC.'],
        imagenUrl: 'https://mercadocompras.co.cr/wp-content/uploads/sites/74/2021/02/image019.png',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'xbox-accesorios', 'acces-mandos']
    },
    {
        id: 20,
        slug: 'nintendo-switch-2',
        nombre: 'Nintendo Switch 2',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Consolas',
        precio: 5000,
        descripcion: 'Consola hibrida para jugar en modo portatil o conectada al televisor.',
        detalles: ['Modo portatil.', 'Modo TV.', 'Ideal para juegos familiares y exclusivos.'],
        imagenUrl: 'https://www.digitaltrends.com/wp-content/uploads/2025/05/nintendo-switch-2-box.png',
        destacado: true,
        popular: true,
        ultimaSalida: true,
        listas: ['inicio-destacados', 'inicio-populares', 'inicio-ultimas-salidas', 'nintendo-consolas']
    },
    {
        id: 21,
        slug: 'nintendo-switch-oled',
        nombre: 'Nintendo Switch OLED',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Consolas',
        precio: 3600,
        descripcion: 'Nintendo Switch con pantalla OLED para colores mas vivos en modo portatil.',
        detalles: ['Pantalla OLED.', 'Modo portatil y TV.', 'Compatible con catalogo Switch.'],
        imagenUrl: 'https://m.media-amazon.com/images/I/61-PblYntsL.jpg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['nintendo-consolas']
    },
    {
        id: 22,
        slug: 'nintendo-switch-2-pack',
        nombre: 'Nintendo Switch 2 Pack',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Consolas',
        precio: 5400,
        descripcion: 'Pack de Nintendo Switch 2 con extras para comenzar a jugar.',
        detalles: ['Consola hibrida.', 'Accesorios incluidos.', 'Ideal para estrenar setup Nintendo.'],
        imagenUrl: 'https://dam.elcorteingles.es/producto/www-0010944630fa01d-00.jpg',
        destacado: false,
        popular: false,
        ultimaSalida: true,
        listas: ['nintendo-consolas']
    },
    {
        id: 23,
        slug: 'nintendo-switch-lite',
        nombre: 'Nintendo Switch Lite',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Consolas',
        precio: 2500,
        descripcion: 'Consola portatil ligera para disfrutar el catalogo de Nintendo Switch.',
        detalles: ['Solo modo portatil.', 'Diseno ligero.', 'Buena opcion de entrada.'],
        imagenUrl: 'https://assets.nintendo.com/image/upload/q_auto:best/f_auto/dpr_2.0/ncom/en_US/products/hardware/nintendo-switch-lite-yellow/110678-nintendo-switch-lite-yellow-package-1200x675',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['nintendo-consolas']
    },
    {
        id: 24,
        slug: 'zelda-totk',
        nombre: 'Zelda TOTK',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Juegos',
        precio: 500,
        descripcion: 'Aventura de mundo abierto para Nintendo con exploracion, puzzles y fantasia.',
        detalles: ['Mundo abierto.', 'Aventura y exploracion.', 'Exclusivo de Nintendo.'],
        imagenUrl: 'https://www.nintendo-master.com/fichiers/2023/4/16/zelda-totk-achat.jpg',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['inicio-populares', 'inicio-ultimas-salidas', 'nintendo-juegos', 'games-nintendo', 'games-ultimas']
    },
    {
        id: 25,
        slug: 'mario-kart-8-deluxe',
        nombre: 'Mario Kart 8 Deluxe',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Juegos',
        precio: 450,
        descripcion: 'Juego de carreras arcade con personajes clasicos de Nintendo.',
        detalles: ['Carreras arcade.', 'Multijugador local.', 'Ideal para jugar en grupo.'],
        imagenUrl: 'https://juegosdigitalesbolivia.com/files/images/productos/1644881577-1637878639-mario-kart-8-deluxe.jpg',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['nintendo-juegos', 'games-nintendo']
    },
    {
        id: 26,
        slug: 'zelda-edicion-especial',
        nombre: 'Zelda Edicion Especial',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Juegos',
        precio: 560,
        descripcion: 'Edicion especial de Zelda para coleccionistas y fans de la saga.',
        detalles: ['Edicion especial.', 'Aventura de mundo abierto.', 'Producto de coleccion.'],
        imagenUrl: 'https://www.nintendo-master.com/fichiers/2023/4/16/zelda-totk-achat.jpg',
        destacado: false,
        popular: false,
        ultimaSalida: true,
        listas: ['nintendo-juegos', 'games-nintendo']
    },
    {
        id: 27,
        slug: 'mario-kart-world',
        nombre: 'Mario Kart World',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Juegos',
        precio: 450,
        descripcion: 'Nueva entrega de carreras de Mario Kart con circuitos y modos renovados.',
        detalles: ['Carreras.', 'Multijugador.', 'Nueva salida Nintendo.'],
        imagenUrl: 'https://media.gamestop.com/i/gamestop/20021637/Mario-Kart-World---Nintendo-Switch-2',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['nintendo-juegos', 'games-nintendo', 'games-ultimas']
    },
    {
        id: 28,
        slug: 'joy-con-neon',
        nombre: 'Joy-Con Neon',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Mandos',
        precio: 750,
        descripcion: 'Par de controles Joy-Con para Nintendo Switch con colores neon.',
        detalles: ['Controles desmontables.', 'Colores neon.', 'Compatible con Nintendo Switch.'],
        imagenUrl: 'https://m.media-amazon.com/images/I/61-PblYntsL.jpg',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['nintendo-accesorios', 'acces-mandos']
    },
    {
        id: 29,
        slug: 'razer-barracuda-x',
        nombre: 'Razer Barracuda X',
        marca: 'Razer',
        plataforma: 'Multiplataforma',
        tipo: 'Auriculares',
        precio: 1300,
        descripcion: 'Auriculares gamer inalambricos para partidas largas y comunicacion clara.',
        detalles: ['Conexion inalambrica.', 'Microfono integrado.', 'Diseno comodo.'],
        imagenUrl: 'https://tse1.mm.bing.net/th/id/OIP.3v1wwVcM1Mf3KRO0w6cxZQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'nintendo-accesorios', 'acces-auriculares']
    },
    {
        id: 30,
        slug: 'redragon-griffin-m607',
        nombre: 'Redragon Griffin M607',
        marca: 'Redragon',
        plataforma: 'Multiplataforma',
        tipo: 'Mouse',
        precio: 500,
        descripcion: 'Mouse gamer RGB con buen agarre y precision para juegos competitivos.',
        detalles: ['Iluminacion RGB.', 'Sensor preciso.', 'Agarre comodo.'],
        imagenUrl: 'https://tse4.mm.bing.net/th/id/OIP.XOToQ2q45yqgB0xRXxm1DwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'nintendo-accesorios', 'acces-mouse']
    },
    {
        id: 31,
        slug: 'silla-gamer-rgb',
        nombre: 'Silla Gamer RGB',
        marca: 'Setup Pro',
        plataforma: 'Multiplataforma',
        tipo: 'Accesorios',
        precio: 2200,
        descripcion: 'Silla gamer con estilo llamativo para completar el escritorio.',
        detalles: ['Diseno gamer.', 'Soporte para sesiones largas.', 'Estilo RGB.'],
        imagenUrl: 'https://m.media-amazon.com/images/I/617HEKLi-BL._AC_UF894,1000_QL80_.jpg',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['nintendo-accesorios']
    },
    {
        id: 32,
        slug: 'mouse-gamer-rgb',
        nombre: 'Mouse Gamer RGB',
        marca: 'Redragon',
        plataforma: 'Multiplataforma',
        tipo: 'Mouse',
        precio: 450,
        descripcion: 'Mouse gamer con iluminacion RGB para uso diario y partidas casuales.',
        detalles: ['RGB.', 'Buen agarre.', 'Cable resistente.'],
        imagenUrl: 'https://tse4.mm.bing.net/th/id/OIP.XOToQ2q45yqgB0xRXxm1DwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-mouse']
    },
    {
        id: 33,
        slug: 'mouse-inalambrico-pro',
        nombre: 'Mouse Inalambrico Pro',
        marca: 'Logitech',
        plataforma: 'Multiplataforma',
        tipo: 'Mouse',
        precio: 650,
        descripcion: 'Mouse inalambrico de baja latencia para trabajo y juego.',
        detalles: ['Conexion inalambrica.', 'Baja latencia.', 'Bateria recargable.'],
        imagenUrl: 'https://tse4.mm.bing.net/th/id/OIP.XOToQ2q45yqgB0xRXxm1DwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-mouse']
    },
    {
        id: 34,
        slug: 'mouse-competitivo',
        nombre: 'Mouse Competitivo',
        marca: 'Razer',
        plataforma: 'Multiplataforma',
        tipo: 'Mouse',
        precio: 720,
        descripcion: 'Mouse enfocado en precision para juegos competitivos.',
        detalles: ['Sensor de alta precision.', 'Peso ligero.', 'Botones laterales.'],
        imagenUrl: 'https://tse4.mm.bing.net/th/id/OIP.XOToQ2q45yqgB0xRXxm1DwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-mouse']
    },
    {
        id: 35,
        slug: 'headset-gamer-rgb',
        nombre: 'Headset Gamer RGB',
        marca: 'HyperX',
        plataforma: 'Multiplataforma',
        tipo: 'Auriculares',
        precio: 900,
        descripcion: 'Headset gamer con iluminacion y microfono para comunicacion en partidas.',
        detalles: ['Microfono integrado.', 'Iluminacion RGB.', 'Almohadillas comodas.'],
        imagenUrl: 'https://tse1.mm.bing.net/th/id/OIP.3v1wwVcM1Mf3KRO0w6cxZQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-auriculares']
    },
    {
        id: 36,
        slug: 'auriculares-inalambricos',
        nombre: 'Auriculares Inalambricos',
        marca: 'Logitech',
        plataforma: 'Multiplataforma',
        tipo: 'Auriculares',
        precio: 1100,
        descripcion: 'Auriculares inalambricos para jugar con libertad de movimiento.',
        detalles: ['Conexion inalambrica.', 'Microfono flexible.', 'Buena autonomia.'],
        imagenUrl: 'https://tse1.mm.bing.net/th/id/OIP.3v1wwVcM1Mf3KRO0w6cxZQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-auriculares']
    },
    {
        id: 37,
        slug: 'redragon-kumara-k552',
        nombre: 'Redragon Kumara K552',
        marca: 'Redragon',
        plataforma: 'Multiplataforma',
        tipo: 'Teclados',
        precio: 700,
        descripcion: 'Teclado mecanico compacto con iluminacion y switches para gaming.',
        detalles: ['Formato compacto.', 'Switches mecanicos.', 'Iluminacion.'],
        imagenUrl: 'https://tse2.mm.bing.net/th/id/OIP.EH4bViyrFmUkxFNEWl5evAHaF1?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: true,
        popular: false,
        ultimaSalida: false,
        listas: ['inicio-destacados', 'acces-teclados']
    },
    {
        id: 38,
        slug: 'teclado-mecanico-rgb',
        nombre: 'Teclado Mecanico RGB',
        marca: 'Redragon',
        plataforma: 'Multiplataforma',
        tipo: 'Teclados',
        precio: 850,
        descripcion: 'Teclado mecanico con iluminacion RGB para setup gamer.',
        detalles: ['Switches mecanicos.', 'RGB configurable.', 'Formato completo.'],
        imagenUrl: 'https://tse2.mm.bing.net/th/id/OIP.EH4bViyrFmUkxFNEWl5evAHaF1?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-teclados']
    },
    {
        id: 39,
        slug: 'teclado-compacto-60',
        nombre: 'Teclado Compacto 60%',
        marca: 'Redragon',
        plataforma: 'Multiplataforma',
        tipo: 'Teclados',
        precio: 650,
        descripcion: 'Teclado compacto 60% para escritorios pequenos y setups minimalistas.',
        detalles: ['Formato 60%.', 'Ahorra espacio.', 'Ideal para transporte.'],
        imagenUrl: 'https://tse2.mm.bing.net/th/id/OIP.EH4bViyrFmUkxFNEWl5evAHaF1?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-teclados']
    },
    {
        id: 40,
        slug: 'teclado-pro-wireless',
        nombre: 'Teclado Pro Wireless',
        marca: 'Logitech',
        plataforma: 'Multiplataforma',
        tipo: 'Teclados',
        precio: 1000,
        descripcion: 'Teclado inalambrico de alto rendimiento para juego y productividad.',
        detalles: ['Conexion inalambrica.', 'Baja latencia.', 'Diseno premium.'],
        imagenUrl: 'https://tse2.mm.bing.net/th/id/OIP.EH4bViyrFmUkxFNEWl5evAHaF1?rs=1&pid=ImgDetMain&o=7&rm=3',
        destacado: false,
        popular: false,
        ultimaSalida: false,
        listas: ['acces-teclados']
    },
    {
        id: 41,
        slug: 'cod-black-ops-cold-war',
        nombre: 'COD Black Ops Cold War',
        marca: 'Activision',
        plataforma: 'Xbox',
        tipo: 'Juegos',
        precio: 400,
        descripcion: 'Shooter de accion con campana y modos multijugador.',
        detalles: ['Accion en primera persona.', 'Campana.', 'Multijugador.'],
        imagenUrl: 'https://placehold.co/600x800/0f2416/ffffff.png?text=COD+Black+Ops+Cold+War',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['games-xbox', 'games-ultimas']
    },
    {
        id: 42,
        slug: 'halo-infinite',
        nombre: 'Halo Infinite',
        marca: 'Xbox Game Studios',
        plataforma: 'Xbox',
        tipo: 'Juegos',
        precio: 430,
        descripcion: 'Juego de accion futurista con campana y multijugador competitivo.',
        detalles: ['Accion futurista.', 'Campana.', 'Multijugador.'],
        imagenUrl: 'https://placehold.co/600x800/0f2416/ffffff.png?text=Halo+Infinite',
        destacado: false,
        popular: false,
        ultimaSalida: true,
        listas: ['games-xbox', 'games-ultimas']
    },
    {
        id: 43,
        slug: 'forza-horizon-5',
        nombre: 'Forza Horizon 5',
        marca: 'Xbox Game Studios',
        plataforma: 'Xbox',
        tipo: 'Juegos',
        precio: 460,
        descripcion: 'Juego de carreras de mundo abierto con autos, eventos y paisajes variados.',
        detalles: ['Carreras.', 'Mundo abierto.', 'Multijugador.'],
        imagenUrl: 'https://placehold.co/600x800/0f2416/ffffff.png?text=Forza+Horizon+5',
        destacado: false,
        popular: true,
        ultimaSalida: true,
        listas: ['games-xbox', 'games-ultimas']
    },
    {
        id: 44,
        slug: 'starfield',
        nombre: 'Starfield',
        marca: 'Bethesda',
        plataforma: 'Xbox',
        tipo: 'Juegos',
        precio: 480,
        descripcion: 'RPG de exploracion espacial con misiones, naves y planetas.',
        detalles: ['RPG espacial.', 'Exploracion.', 'Campana individual.'],
        imagenUrl: 'https://placehold.co/600x800/0f2416/ffffff.png?text=Starfield',
        destacado: false,
        popular: false,
        ultimaSalida: true,
        listas: ['games-xbox', 'games-ultimas']
    },
    {
        id: 45,
        slug: 'gran-turismo-7',
        nombre: 'Gran Turismo 7',
        marca: 'Polyphony Digital',
        plataforma: 'PlayStation',
        tipo: 'Juegos',
        precio: 430,
        descripcion: 'Simulador de carreras para PlayStation con autos detallados y competiciones.',
        detalles: ['Carreras.', 'Simulacion.', 'Exclusivo de PlayStation.'],
        imagenUrl: 'https://placehold.co/600x800/151515/ffffff.png?text=Gran+Turismo+7',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['games-ps', 'games-ultimas']
    },
    {
        id: 46,
        slug: 'super-mario-odyssey',
        nombre: 'Super Mario Odyssey',
        marca: 'Nintendo',
        plataforma: 'Nintendo',
        tipo: 'Juegos',
        precio: 430,
        descripcion: 'Aventura de plataformas de Mario con mundos variados y exploracion.',
        detalles: ['Plataformas.', 'Aventura.', 'Exclusivo de Nintendo.'],
        imagenUrl: 'https://placehold.co/600x800/bb0011/ffffff.png?text=Super+Mario+Odyssey',
        destacado: false,
        popular: true,
        ultimaSalida: false,
        listas: ['games-nintendo', 'games-ultimas']
    }
];

function formatoPrecio(precio) {
    return 'Bs. ' + Number(precio).toLocaleString('es-BO');
}

function obtenerArticuloPorSlug(slug) {
    return articulos.find(function(articulo) {
        return articulo.slug === slug;
    });
}

function obtenerArticuloPorId(id) {
    return articulos.find(function(articulo) {
        return articulo.id === Number(id);
    });
}
